apiVersion: v1
kind: ConfigMap
metadata:
  name: book-app-postgres-config
  namespace: book-app-ns
data:
  POSTGRES_DB: 'bookdb'
  POSTGRES_USER: 'postgres'
---
apiVersion: v1
kind: Secret
metadata:
  name: book-app-postgres-secret
  namespace: book-app-ns
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bW9uaWthMTIz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-app-postgres-pvc
  namespace: book-app-ns
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: book-app-postgres-statefulset
  namespace: book-app-ns
spec:
  serviceName: book-app-postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: book-app-ns
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: book-app-postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: book-app-postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: book-app-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: book-app-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: book-app-postgres-data
          persistentVolumeClaim:
            claimName: book-app-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: book-app-postgres-service
  namespace: book-app-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
  type: LoadBalancer
